auto: true
server: true
pygments: true
permalink: none
baseurl: ""
oauth_client_id: c602a8bd54b1e774f864
gatekeeper_url: http://prose-gatekeeper.herokuapp.com
exclude: [".rvmrc", ".rbenv-version", ".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]
